#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Author: Marius Pana <mp@sphs.ro>

# EXAMPLE DATA FROM: 
# fomat: emailaddress size_in_MB
#<<<exchange_user_mbx_size>>>
#marius.pana@sphs.ro 177
#mpana@sphs.ro 81

exchange_user_mbx_size_default_values = (1500, 2000)

def inventory_exchange_user_mbx_size(info):
    inventory = []
    for line in info:
        useremail = line[0]
        mailboxsize = line[1]
        inventory.append( (useremail, "exchange_user_mbx_size_default_values") )
    return inventory


def check_exchange_user_mbx_size(item, params, info):
    #unpack check params
    warn, crit = params
    for line in info:
        if line[0] == item:
            mailboxsize = int(line[1])
            perfdata = [ ( "size", mailboxsize, warn, crit  )  ]
            if mailboxsize > crit:
                return (2, "Mailbox size is %dMB" % mailboxsize, perfdata)
            elif mailboxsize > warn:
                return (1, "Mailbox size is %dMB" % mailboxsize, perfdata)
            else:
                return (0, "Mailbox size is %dMB" % mailboxsize, perfdata)
    return(3, "Mailbox %s not found in agent output" % item)

check_info["exchange_user_mbx_size"] = {
    'check_function':        check_exchange_user_mbx_size,
    'inventory_function':    inventory_exchange_user_mbx_size,
    'service_description':   '%s Mailbox size',
    'has_perfdata':          True,
    'group':                 'exchange_user_mbx_size',
}
